services:
    # PostgreSQL Database
    db:
        image: postgres:15-alpine
        environment:
            POSTGRES_DB: django_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 10s
            timeout: 5s
            retries: 5

    # Django Backend
    backend:
        build: ./backend
        env_file:
            - ./backend/.env.prod
        volumes:
            - backend_static:/app/staticfiles
            - backend_media:/app/media
            - ./resources:/app/resources:ro
        depends_on:
            db:
                condition: service_healthy
        ports:
            - '8000:8000'

    # React Frontend
    frontend:
        build: ./frontend
        environment:
            - REACT_APP_API_URL=http://localhost/api
        depends_on:
            - backend
        ports:
            - '3000:80'

    # Nginx Reverse Proxy
    nginx:
        image: nginx:alpine
        ports:
            - '80:80'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - backend_static:/static:ro
        depends_on:
            - backend
            - frontend

volumes:
    postgres_data:
    backend_static:
    backend_media:
