services:
    # PostgreSQL Database
    db:
        image: postgres:15-alpine
        env_file:
            - ./backend/.env.prod
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 10s
            timeout: 5s
            retries: 5
        restart: unless-stopped

    # Django Backend (serves both API and React frontend)
    backend:
        build: .
        env_file:
            - ./backend/.env.prod
        volumes:
            - backend_media:/app/media
            - ./resources:/app/resources:ro
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        depends_on:
            db:
                condition: service_healthy
        restart: unless-stopped
        ports:
            - '80:8000'
            - '443:8443'
        deploy:
            resources:
                limits:
                    memory: 800M
                reservations:
                    memory: 400M

    # Certbot for SSL certificates
    certbot:
        image: certbot/certbot
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        command: certonly --webroot -w /var/www/certbot --force-renewal --email your-email@example.com -d idonotlikedocker.com --agree-tos

volumes:
    postgres_data:
    backend_media:
