services:
    # PostgreSQL Database
    db:
        image: postgres:15-alpine
        env_file:
            - ./backend/.env.prod
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 10s
            timeout: 5s
            retries: 5
        restart: unless-stopped

    # Django Backend
    backend:
        build: ./backend
        env_file:
            - ./backend/.env.prod
        volumes:
            - backend_static:/app/staticfiles
            - backend_media:/app/media
            - ./resources:/app/resources:ro
        depends_on:
            db:
                condition: service_healthy
        restart: unless-stopped

    # React Frontend
    frontend:
        build: ./frontend
        environment:
            - REACT_APP_API_URL=https://idonotlikedocker.com/api
        depends_on:
            - backend
        restart: unless-stopped

    # Nginx Reverse Proxy
    nginx:
        image: nginx:alpine
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - backend_static:/static:ro
        depends_on:
            - backend
            - frontend
        restart: unless-stopped

volumes:
    postgres_data:
    backend_static:
    backend_media:
